### PR TITLE
Enable logging

### PR DESCRIPTION
**Pull request by tmcgroul**

### CODE REVIEW

**Comment by BehindLoader** [comment]
@tmcgroul Is this logger is asynchronous?

**Comment by tmcgroul** [comment]
@BehindLoader no :crying_cat_face:

**Comment by tmcgroul** [comment]
i'll fix it with https://github.com/B2W-BIT/aiologger

**Comment by tmcgroul** [comment]
@BehindLoader i was trying to replace standart logger to [aiologger](https://github.com/B2W-BIT/aiologger) and i got same performance for both variants. I checked with [HTTP benchmarking tool](https://github.com/wg/wrk).

aiohttp v4 will be "better" for async logging. Maybe we change logger to async in future.
https://docs.aiohttp.org/en/latest/logging.html

You can merge this pr!

**Pull request merged**
